//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.PowerToys.Run.Plugin.PowerToysCommands.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.PowerToys.Run.Plugin.PowerToysCommands.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run PowerToys Color Picker.
        /// </summary>
        public static string CommandColorPickerSubTitle {
            get {
                return ResourceManager.GetString("CommandColorPickerSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerToys Color Picker.
        /// </summary>
        public static string CommandColorPickerTitle {
            get {
                return ResourceManager.GetString("CommandColorPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run PowerToys FancyZones Editor.
        /// </summary>
        public static string CommandFancyZonesEditorSubTitle {
            get {
                return ResourceManager.GetString("CommandFancyZonesEditorSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerToys FancyZones Editor.
        /// </summary>
        public static string CommandFancyZonesEditorTitle {
            get {
                return ResourceManager.GetString("CommandFancyZonesEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run PowerToys Screen Ruler.
        /// </summary>
        public static string CommandMeasureToolSubTitle {
            get {
                return ResourceManager.GetString("CommandMeasureToolSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerToys Screen Ruler.
        /// </summary>
        public static string CommandMeasureToolTitle {
            get {
                return ResourceManager.GetString("CommandMeasureToolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run PowerToys Text Extractor.
        /// </summary>
        public static string CommandPowerOCRSubTitle {
            get {
                return ResourceManager.GetString("CommandPowerOCRSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerToys Text Extractor.
        /// </summary>
        public static string CommandPowerOCRTitle {
            get {
                return ResourceManager.GetString("CommandPowerOCRTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show PowerToys Shortcut Guide.
        /// </summary>
        public static string CommandShortcutGuideSubTitle {
            get {
                return ResourceManager.GetString("CommandShortcutGuideSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerToys Shortcut Guide.
        /// </summary>
        public static string CommandShortcutGuideTitle {
            get {
                return ResourceManager.GetString("CommandShortcutGuideTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run PowerToys commands from PowerToys Run.
        /// </summary>
        public static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerToys Commands Plugin.
        /// </summary>
        public static string PluginTitle {
            get {
                return ResourceManager.GetString("PluginTitle", resourceCulture);
            }
        }
    }
}
